theme:
  name: material
  highlightjs: True
  hljs_style: shades-of-purple
  locale: es
  language: gl
  include_homepage_in_sidebar: True
  prev_next_buttons_location: both
  favicon: "images/favicon.png"
  logo: "images/logo.png"
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.indexes
    - toc.follow
#    - toc.integrate
    - navigation.top
    - navigation.path
    - navigation.prune
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Modo oscuro (da calambre)
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Modo normal
      primary: green
      accent: ambe
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
nav:
  - "ğŸ“š Inicio â€” PresentaciÃ³ns": "index.md"
  - "ğŸ‘· Contorno/ConfiguraciÃ³ns":
      - "ğŸ Contorno BigData": "conda-0-config-basica.md"
      - "ğŸ§ WSL": "windows-wsl.md"
      - "ğŸ”µ Docker": "docker-0-base-simple.md"
      - "ğŸ³ Bases de Datos":
        - "ğŸ§¾ MySQL / MariaDB": "docker-1-my-maria.md"
        - "ğŸ§¾ PostgreSQL": "docker-4-postgresql.md"
        - "ğŸ§¾ MongoDB": "docker-2-mongodb.md"
        - "ğŸ§¾ Redis": "docker-3-redis.md"
        - "ğŸ§¾ Microsoft SQL Server": "docker-5-mssql-server.md"
        - "ğŸ§¾ Oracle Free": "docker-6-oracle.md"
      - "ğŸ¦« DBeaver e tÃºneles SSH": "dbeaver-tunel-ssh.md"
      - "ğŸ”‘ SSH e tÃºneles": "ssh-0-chaves-tuneles.md"
      - "â˜• Java/OpenJDK/Corretto": "amazon-corretto-java-0-instalacion.md"
      - "ğŸª„ Ipython mÃ¡xico": "python-1-maxias.md"
      - "ğŸ—‚ï¸ Arquivos en Python": "python-0-conceptos-previos.md"
      - "ğŸ“˜ Docker ++": "docker-z-guia-refinitiva.md"
  - "ğŸ˜ Apache Hadoop":
    - "ğŸ§¾ InstalaciÃ³n": "apache-hadoop-0-instalacion.md"
    - "ğŸ”² Comandos": "apache-hadoop-1-comandos.md"
    - "ğŸ§® Exemplo contapalabras": "apache-hadoop-2-cuentapalabras.md"
  - "âš Apache Spark":
    - "ğŸ§¾ InstalaciÃ³n": "apache-spark-0-instalacion.md"
    - "ğŸ”² Comandos": "apache-spark-1-comandos.md"
  - "â¿ Apache Kafka": 
    - "ğŸ³ InstalaciÃ³n docker": "apache-kafka-0-instalacion-docker.md"
    - "ğŸœï¸ Conceptos bÃ¡sicos": "apache-kafka-1-conceptos-basicos.md"
    - "ğŸ Kafka e Python" : "apache-kafka-2-python.md"
    - "âš Kafka e Spark": "apache-kafka-3-spark.md"
    - "ğŸ’§ Kafka e Nifi": "apache-kafka-4-nifi.md"
  - "ğŸ’§ Apache NIFI":
    - "ğŸ³ InstalaciÃ³n docker": "apache-nifi-0-instalacion.md"
    - "ğŸ‘‰ï¸ InstalaciÃ³n manual": "apache-nifi-0-instalacion-manual.md"
    - "ğŸœï¸ Conceptos previos": "apache-nifi-1-conceptos-previos.md"
    - "ğŸ‘£ Primeiros pasos": "apache-nifi-1-primeiros-pasos.md"
    - "ğŸ‘· Procesadores": "apache-nifi-4-procesadores.md"
    - "ğŸŒ CodificaciÃ³n de caracteres" : "apache-nifi-3-codificacion.md"
    - "ğŸ¯ ParÃ¡metros": "apache-nifi-2-parametros.md"
    - "ğŸ˜¼ Control de versiÃ³ns": "apache-nifi-z-control-versions.md"
  - "ğŸ‡¸ Apache Sqoop": "apache-sqoop-0-resumo.md"
  - "ğŸ€ Apache Airflow": "apache-airflow-0-instalacion.md"
  - "â™¾ï¸ Apache Superset": "apache-superset.md"
  - "â˜ï¸ Nube/Cloud/Openstack":
    - "â˜ï¸ IntroduciÃ³n": "nube-0-intro.md"
    - "â• Crear Instancia": "nube-1-openstack-crear-lanzar-instancia.md"
    - "ğŸ’¿ VolÃºmenes": "nube-2-openstack-volumes.md"
    - "ğŸ›¡ï¸ Grupos de seguridade": "nube-3-openstack-grupos-seguridade.md"
    - "â›ˆï¸ RecuperaciÃ³n": "nube-4-openstack-recovey.md"
    - "ğŸ¢ SWAP": "nube-5-openstack-crear-swap.md"
    - "âš™ï¸ Automatizando": "nube-6-comandos.md"
  - "ğŸ“¶ Microsoft PowerBi": "powerbi-0-python.md"
  - "ğŸ—’ï¸ Plantillas docencia": "https://github.com/jfsanchez/docencia/tree/main/libreta"
extra_css:
  - _res/extra.css
#   - _res/prism.css
# extra_javascript:
#   - _res/prism.js
site_name: JFSanchez
site_url: https://jfsanchez.es/
repo_url: https://github.com/jfsanchez/
site_author: Jose SÃ¡nchez
copyright: 2025 - Jose SÃ¡nchez
#plugins:
#  - search
#  - pdf-export:
#      verbose: true
#      media_type: print
#      enabled_if_env: ENABLE_PDF_EXPORT
