theme:
  name: material
  highlightjs: True
  hljs_style: shades-of-purple
  locale: es
  language: gl
  include_homepage_in_sidebar: True
  prev_next_buttons_location: both
  favicon: "images/favicon.png"
  logo: "images/logo.png"
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.indexes
    - toc.follow
#    - toc.integrate
    - navigation.top
    - navigation.path
    - navigation.prune
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Modo oscuro (da calambre)
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Modo normal
      primary: green
      accent: ambe
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
nav:
  - "ğŸ“š Inicio": "index.md"
  - "ğŸª¶ Apache Hadoop":
    - "ğŸ§¾ InstalaciÃ³n": "apache-hadoop-0-instalacion.md"
    - "ğŸ”² Comandos": "apache-hadoop-1-comandos.md"
  - "âš Apache Spark":
    - "ğŸ§¾ InstalaciÃ³n": "apache-spark-0-instalacion.md"
  - "ğŸï¸ Apache NIFI":
    - "ğŸ§¾ InstalaciÃ³n": "apache-nifi-0-instalacion.md"
  - "ğŸ‡¸ Apache sqoop": "apache-sqoop-0-resumo.md"
  - "ğŸ Conda e Python":
    - "ğŸ§¾ Contorno BigData": "conda-0-config-basica.md"
    - "ğŸª„ Ipython mÃ¡xico": "python-1-maxias.md"
    - "ğŸ’Š Arquivos en Python": "python-0-conceptos-previos.md"
  - "ğŸ¦« DBeaver e tÃºneles SSH": "dbeaver-tunel-ssh.md"
  - "ğŸ”µ Docker":
    - "ğŸ GuÃ­a bÃ¡sica": "docker-0-base-simple.md"
    - "ğŸ§¾ MySQL / MariaDB": "docker-1-my-maria.md"
    - "ğŸ§¾ MongoDB": "docker-2-mongodb.md"
    - "ğŸ§¾ Redis": "docker-3-redis.md"
    - "ğŸ§¾ PostgreSQL": "docker-4-postgresql.md"
    - "ğŸ§¾ Microsoft SQL Server": "docker-5-mssql-server.md"
    - "ğŸ§¾ Apache Nifi": "docker-8-apache-nifi.md"
    - "ğŸ§¾ Oracle Free": "docker-6-oracle.md"
    - "ğŸ§¾ Kafka": "docker-7-kafka.md"
    - "ğŸ“˜ La guÃ­a refinitiva": "docker-z-guia-refinitiva.md"
  - "â˜ï¸ Nube/Cloud/Openstack":
    - "â˜ï¸ IntroduciÃ³n": "nube-0-intro.md"
    - "ğŸ”‘ SSH e tÃºneles": "ssh-0-chaves-tuneles.md"
    - "â• Crear Instancia": "nube-1-openstack-crear-lanzar-instancia.md"
    - "ğŸ’¿ VolÃºmenes": "nube-2-openstack-volumes.md"
    - "ğŸ›¡ï¸ Grupos de seguridade": "nube-3-openstack-grupos-seguridade.md"
    - "â›ˆï¸ RecuperaciÃ³n": "nube-4-openstack-recovey.md"
    - "ğŸ¢ SWAP": "nube-5-openstack-crear-swap.md"
  - "ğŸ§ PowerBi e Python": "powerbi-0-python.md"
  - "ğŸŒªï¸ WSL": "windows-wsl.md"
  - "ğŸ–¨ï¸ Plantillas docencia": "https://github.com/jfsanchez/docencia/tree/main/libreta"
extra_css:
  - _res/extra.css
#   - _res/prism.css
# extra_javascript:
#   - _res/prism.js
site_name: JFSanchez
site_url: https://jfsanchez.es/
repo_url: https://github.com/jfsanchez/
site_author: Jose SÃ¡nchez
copyright: 2025 - Jose SÃ¡nchez
